// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx3M1feW5icvK6_S3iXY1Ai9gYxNmjfUA',
    appId: '1:425869071166:web:f7436ebf93ef3839a3926f',
    messagingSenderId: '425869071166',
    projectId: 'sezenaksu-96ae5',
    authDomain: 'sezenaksu-96ae5.firebaseapp.com',
    storageBucket: 'sezenaksu-96ae5.appspot.com',
    measurementId: 'G-LFJ795KJ4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCf2NFFeyywKrkwBePZ0cyP33eJyWNpL4',
    appId: '1:425869071166:android:f87b10b3c94382a3a3926f',
    messagingSenderId: '425869071166',
    projectId: 'sezenaksu-96ae5',
    storageBucket: 'sezenaksu-96ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChR0HP6cccvsGX-Z9Vz8DXaOMtq48AleU',
    appId: '1:425869071166:ios:d79ec0b013f53b2ba3926f',
    messagingSenderId: '425869071166',
    projectId: 'sezenaksu-96ae5',
    storageBucket: 'sezenaksu-96ae5.appspot.com',
    iosBundleId: 'com.example.littleBute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChR0HP6cccvsGX-Z9Vz8DXaOMtq48AleU',
    appId: '1:425869071166:ios:d2b5be460352544da3926f',
    messagingSenderId: '425869071166',
    projectId: 'sezenaksu-96ae5',
    storageBucket: 'sezenaksu-96ae5.appspot.com',
    iosBundleId: 'com.example.littleBute.RunnerTests',
  );
}
